version: '3.7'

services:
  db:
    image: postgres:12
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: root
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: